# -*- coding: utf-8 -*-
"""Ucentral_Sistema_evaluacion_creacion_cupos_para_clientes_Vargas_Barrera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GEl-4EbZqj92lV6LtZoVtQfc0z6o6TJ

# **Ucentral_Sistema_evaluacion_creacion_cupos_para_clientes_Vargas_Barrera**

**Integrantes:** Edwin Giobany Vargas Parra y Laura Camila Barrera Sánchez

**Institución:** Universidad Central

Este notebook automatiza el flujo de decisión para la creación de un cliente en una compañía de consumo masivo mediante las siguientes etapas:

*   **Validación SARLAFT/OFAC:** Bloqueo de clientes reportados en listas restrictivas.
*   **Evaluación de Riesgo Crediticio:** Análisis del comportamiento financiero y crediticio en otras compañías
*    **Parametrización del crédito:** Asignación de aprobación, cupo y plazo del crédito otorgado.
* El analisis se realizó una convinación de valores simulados y valores. detallar mas

***Enlace de descarga de las muestras utilizadas***

*   **Lista ofact:** https://raw.githubusercontent.com/evargasp4-boop/Ucentral_Sistema_evaluaci-n_creacion_cupos_para_clientes_Vargas_Barrera/refs/heads/main/ofac.csv

*    **Muestra de clientes:** https://raw.githubusercontent.com/evargasp4-boop/Ucentral_Sistema_evaluaci-n_creacion_cupos_para_clientes_Vargas_Barrera/refs/heads/main/Muestra%20de%20clientes.csv

*    **Base buró:**  https://raw.githubusercontent.com/evargasp4-boop/Ucentral_Sistema_evaluaci-n_creacion_cupos_para_clientes_Vargas_Barrera/refs/heads/main/Base%20Bur%C3%B3.csv

## **1. Importar librerias**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## **2. Cargar bases de datos**"""

# Carga de la lista OFAC (no contiene encabezados)
url_ofac = 'https://raw.githubusercontent.com/evargasp4-boop/Ucentral_Sistema_evaluaci-n_creacion_cupos_para_clientes_Vargas_Barrera/refs/heads/main/ofac.csv'
ofac = pd.read_csv(url_ofac, header=None)

# Carga de la base del Buró
url_buro = 'https://raw.githubusercontent.com/evargasp4-boop/Ucentral_Sistema_evaluaci-n_creacion_cupos_para_clientes_Vargas_Barrera/refs/heads/main/Base%20Bur%C3%B3.csv'
buro = pd.read_csv(url_buro)

# Carga de solicitudes de creación de clientes
url_clients = 'https://raw.githubusercontent.com/evargasp4-boop/Ucentral_Sistema_evaluaci-n_creacion_cupos_para_clientes_Vargas_Barrera/refs/heads/main/Muestra%20de%20clientes.csv'
sample_clients = pd.read_csv(url_clients)

"""## **3. Limpieza y Homogeneización de Datos**

#### 3.1.  Normalización lista OFAC
"""

# Renombrar columnas de la base OFAC para identificar los datos de cada columna

ofac = ofac.rename(columns={0: 'id',
                            1: 'name',
                            2: 'individual_or_group',
                            3: 'country',
                            4: 'reported_by',
                            11: 'address'})


# Estandarización en minúsculas y eliminación de espacios
columnas_en_str = ['name', 'individual_or_group', 'country', 'reported_by']

for columna in columnas_en_str:
    ofac.loc[:, columna] = ofac[columna].astype(str).str.strip().str.lower()

# Revisión de validez del Id del cliente
#ofac_list['id'] = np.where(ofac_list['id'].astype(str).str.isnumeric(), ofac_list['id'], 'id_invalido')
# copia de ofac a ofac_list


# Eliminar las comas en la columna de nombres
ofac['name'] = ofac['name'].str.replace(",", "", regex=False)

# Sacar copia de base ofac
ofac_list = ofac.copy()

"""3.2. Normalización muestra de clientes"""

# Estandarización en minúsculas y eliminación de espacios y comas en la columna de nombres
sample_clients['nombre_cliente'] = sample_clients['nombre_cliente'].astype(str).str.lower().str.replace(",", "", regex=False)

"""3.3. Ordenamiento del nombre del cliente"""

sample_clients.head()

# Con el objetivo de evitar diferencias en el orden de nombres y apellidos que puedan afectar el cruce, se ordenan de manera alfabetica las palabras que componen el nombre.
def ordenar_nombre(texto):
   if texto in ['nan', 'sin_informacion']:
        return texto
   return ' '.join(sorted(texto.split()))

ofac_list['name'] = ofac_list['name'].apply(ordenar_nombre)

sample_clients['nombre_cliente'] = sample_clients['nombre_cliente'].apply(ordenar_nombre)

# Sacar copia de base ofac
consolidado = sample_clients.copy()

"""## **4. Cruce Muestra de Clientes vs. Lista OFAC**"""

# Marcar si el cliente está en lista OFAC
consolidado["esta_en_ofac"] = consolidado['nombre_cliente'].isin(ofac_list["name"]).map({True: "si", False: "no"})

"""## **5. Limpieza de los datos: Valores en moneda, Cuotas y Datos del Buró**

5.1. Conversión de campos con moneda a float
"""

# Definición de la función para limpiar datos de montos
def arreglar_num(texto):
    texto = str(texto)
    if texto in ['nan', 'sin_informacion', '']:
        return 0.0
    else:
        limpio = texto.replace("$", "").replace(",", "").replace("COP", "").replace(" ", "").replace("nan", "0").replace(" ", "")
        return float(limpio)

# Aplicar función para la limpieza de montos en muestra de clientes y buró
consolidado['cupo_preaprobado'] = consolidado['cupo_preaprobado'].apply(arreglar_num)
buro['ingresos_ano_anterior'] = buro['ingresos_ano_anterior'].apply(arreglar_num)
buro['egresos_ano_anterior'] = buro['egresos_ano_anterior'].apply(arreglar_num)
buro['valor_credito_mora'] = buro['ingresos_ano_anterior'].apply(arreglar_num)

"""5.2. Limpieza de edad, cuotas en mora y quitar duplicados"""

# Limpiar texto en cuotas y edad
buro['numero_cuotas_mora'] = buro['numero_cuotas_mora'].astype(str).str.replace("cuotas", "", regex=False)
buro['numero_cuotas_mora']= buro['numero_cuotas_mora'].astype(float)

# Eliminar duplicados en Buró conservando el primer registro por cliente
buro = buro.sort_values(
    by=[
        "id_cliente",
        "ingresos_ano_anterior",
        "egresos_ano_anterior",
        "valor_credito_mora",
        "numero_cuotas_mora",
        "edad"
    ],
    ascending=False
).reset_index(drop=True)

buro["rep"] = buro.groupby("id_cliente").cumcount() + 1
buro = buro[buro["rep"] == 1].reset_index(drop=True)

"""## **6. Cruce Muestra de Clientes vs. Buró**"""

# Agregar al consolidado los datos necesarios para asignar el nivel de riesgo
consolidado = consolidado.merge(
    buro[
        ['id_cliente',
         'ingresos_ano_anterior',
         'egresos_ano_anterior',
         'valor_credito_mora',
         'numero_cuotas_mora',
         'edad']
    ],
    on='id_cliente',
    how='left'
)

# Eliminar duplicados del consolidado
consolidado = consolidado.drop_duplicates()

"""## **7. Asignación del nivel de riesgo**"""

# Función para clasificar el nivel de riesgo de acuerdo con los parametros establecidos por la compañía
def clasificar_riesgos(ingresos_ano_anterior, egresos_ano_anterior, valor_credito_mora, numero_cuotas_mora):

    if ingresos_ano_anterior <= 0 or egresos_ano_anterior < 0:
        return 'alto'

    elif (ingresos_ano_anterior > egresos_ano_anterior and valor_credito_mora <= ingresos_ano_anterior * 1.50 and numero_cuotas_mora <= 4):
        return 'bajo'

    elif (ingresos_ano_anterior > egresos_ano_anterior and (valor_credito_mora <= ingresos_ano_anterior * 2.00 or numero_cuotas_mora <= 6)):
        return 'medio'

    else:
        return 'alto'


consolidado["nivel_riesgo"] = consolidado[
    ["ingresos_ano_anterior",
     "egresos_ano_anterior",
     "valor_credito_mora",
     "numero_cuotas_mora"]
].apply(lambda fila: clasificar_riesgos(*fila), axis=1)

"""## **8. Estandarización del formato de la fecha de solicitud**"""

# Función para la estandarización de la fecha eliminando espacios, separadores y
def unificar_fecha_pandas(columna):
    s = columna.astype(str).str.strip().str.split(' ').str[0]
    s = s.str.replace('.', '-', regex=False)
    fechas_dt = pd.to_datetime(s, format='mixed', dayfirst=True, errors='coerce')
    fechas_formateadas = fechas_dt.dt.strftime('%Y-%m-%d')
    resultado = np.where(columna.isna() | (columna.astype(str).str.strip() == ''), np.nan, fechas_formateadas)

    return pd.Series(resultado, index=columna.index)

# Aplicar al DataFrame
consolidado['fecha_solicitud'] = unificar_fecha_pandas(consolidado['fecha_solicitud'])

# Fecha to Date time
consolidado['fecha_solicitud'] = pd.to_datetime(
    unificar_fecha_pandas(consolidado['fecha_solicitud'])
)

"""## **9. Estandarización del formato de la edad**"""

# Primero convertir la columna edad a número:
consolidado['edad'] = pd.to_numeric(consolidado['edad'], errors='coerce')
# Aplicar la función al df consolidado
consolidado['aprobacion'] = consolidado.apply(
    lambda fila: aprobado(
        fila['esta_en_ofac'],
        fila['nivel_riesgo'],
        fila['edad']
    ),
    axis=1
)

"""## **10. Aprobación del crédito**"""

# Definir si el crédito no se aprueba, se aprueba de contado o a crédito
def aprobado(esta_en_ofac, nivel_riesgo, edad):
    if edad < 18 or esta_en_ofac=="si":
        return 'no aprobado'
    elif nivel_riesgo=="alto":
        return 'aprobado de contado'
    else:
        return 'aprobado a credito'

"""## **11. Definición de valor_pedido, cupo_aprobado y plazo según riesgo y estado de aprobación**"""

# C
consolidado['valor_pedido'] = consolidado['cupo_preaprobado']

def calcular_cupo(row):

    if row['aprobacion'] == 'no aprobado' or row['nivel_riesgo'] == 'alto':
        return 0
    elif row['nivel_riesgo'] == 'medio':
        return row['cupo_preaprobado'] * 0.50
    elif row['nivel_riesgo'] == 'bajo':
        return row['cupo_preaprobado'] * 1.00
    return 0

def calcular_plazo(row):
    # Si no es aprobado o tiene riesgo alto -> Plazo 0 días
    if row['aprobacion'] == 'no aprobado' or row['nivel_riesgo'] == 'alto':
        return '0 días'
    elif row['nivel_riesgo'] == 'medio':
        return '15 días'
    elif row['nivel_riesgo'] == 'bajo':
        return '45 días'
    return '0 días'

consolidado['cupo_aprobado'] = consolidado.apply(calcular_cupo, axis=1)
consolidado['plazo'] = consolidado.apply(calcular_plazo, axis=1)


# Selección de la base consolidada final únicamente con las columnas requeridas
consolidado_final = consolidado[[
    'id_cliente',
    'nombre_cliente',
    'producto',
    'fecha_solicitud',
    'nivel_riesgo',
    'aprobacion',
    'valor_pedido',
    'cupo_aprobado',
    'plazo'
]]

# 1. Crear la base final realizando una copia explícita
base_final = consolidado[[
    'id_cliente',
    'nombre_cliente',
    'producto',
    'fecha_solicitud',
    'nivel_riesgo',
    'aprobacion',
    'valor_pedido',
    'cupo_aprobado',
    'plazo'
]].copy()

# 2. Asegurar la conversión numérica
base_final['valor_pedido'] = pd.to_numeric(base_final['valor_pedido'], errors='coerce').fillna(0)
base_final['cupo_aprobado'] = pd.to_numeric(base_final['cupo_aprobado'], errors='coerce').fillna(0)

# 3. Aplicar formato de miles sin advertencias
base_final['valor_pedido'] = base_final['valor_pedido'].apply(lambda x: f"{int(x):,}".replace(",", "."))
base_final['cupo_aprobado'] = base_final['cupo_aprobado'].apply(lambda x: f"{int(x):,}".replace(",", "."))

kpi_aprobacion = (
    consolidado
    .groupby(['aprobacion', 'producto'], as_index=False)
    .agg(
        solicitudes=('nombre_cliente', 'size'),
        valor=('cupo_preaprobado', 'sum'),
        edad_prom=('edad', 'mean'),
    )
)
kpi_aprobacion['ticket_promedio'] = (kpi_aprobacion['valor'] / kpi_aprobacion['solicitudes']).round(2)
kpi_aprobacion['edad_prom'] = kpi_aprobacion['edad_prom'].round(0)
kpi_aprobacion

consolidado.head()

base_final.info()

"""## **12. Gráficas para resumen ejecutivo**

### * **Grafico de barras: agrupamiento para grafica de barras agrupando por producto sumento el valor del pedido en millones$$.**
"""

# agrupamiento para grafica de barras agrupando por producto sumento el valor del pedido en millones$$.
productos = consolidado.groupby('producto')['valor_pedido'].sum().sort_values()/1000000

#grafico de barras
total_monto_preaprobado =productos.sum()
figura, eje = plt.subplots(figsize=(8, 4.5))
colores = ['#009DAE', '#FF6B6B', '#FFD166', '#06D6A0', '#118AB2', '#8338EC']
eje.barh(productos.index, productos.values, color=colores[:len(productos)])
eje.set_title(f'Productos Solicitados — Total pedidos: {total_monto_preaprobado:,.0f}'.replace(',', '.'))
eje.set_xlabel('valor_pedido_millones')
plt.tight_layout()
plt.show()

"""### * **Cantidad de solicitudes: Agrupamiento de la cantidad solicitudes por respuesta a la solicitud**"""

#Agrupamiento de cantidad de solicitudes y respuesta
Cantidad_solicitudes = (
    consolidado.groupby('aprobacion')['id_cliente']
    .count()
    .sort_values()
)

#Gráfico de barras
total_solicitudes = Cantidad_solicitudes.sum()
figura, eje = plt.subplots(figsize=(8, 4.5))
colores = ['#009DAE', '#FF6B6B', '#FFD166', '#06D6A0', '#118AB2', '#8338EC']
barras = eje.barh(Cantidad_solicitudes.index,Cantidad_solicitudes.values, color=colores[:len(Cantidad_solicitudes)])
# Etiquetas de cada barra
eje.bar_label(barras, padding=5, fmt='%.0f')
eje.set_title(f'Clientes — Total: {total_solicitudes:,.0f}'.replace(',', '.'))
eje.set_xlabel('Cantidades')
plt.tight_layout()
plt.show()

"""

###* **Cantidad de clientes solicitantes: Agrupamiento de cantidad distinta de id clientes**

"""

#Agrupamiento de cantidad de clientes distintos y respuesta
cantidad_por_resultado = (
    consolidado.groupby('aprobacion')['id_cliente']
    .nunique()
    .sort_values()
)

# Gráfico de barras por cantidad de clientes distintos
total_clientes = cantidad_por_resultado.sum()

figura, eje = plt.subplots(figsize=(8, 4.5))
colores = ['#009DAE', '#FF6B6B', '#FFD166', '#06D6A0', '#118AB2', '#8338EC']
barras = eje.barh(
    cantidad_por_resultado.index,
    cantidad_por_resultado.values,
    color=colores[:len(cantidad_por_resultado)]
)

# Etiquetas con la cantidad de clientes
eje.bar_label(barras, padding=5, fmt='%.0f')

eje.set_title(f'Clientes — Total: {total_clientes:,.0f}'.replace(',', '.'))
eje.set_xlabel('Cantidades')

plt.tight_layout()
plt.show()

"""### * **Monto total aprobado frente al nivel de riesgo.**"""

# Agrupamiento monto aprobado y nivel de riesgo
monto_aprobado = (consolidado.groupby('nivel_riesgo')['cupo_aprobado'].sum().sort_values())/1000000

# Grafico de monto aprobado y nivel de riesgo
total_monto_aprobadoMM = monto_aprobado.sum()
figura, eje = plt.subplots(figsize=(8, 4.5))
colores = ['#009DAE', '#FF6B6B', '#FFD166', '#06D6A0', '#118AB2', '#8338EC']
barras = eje.barh(
    monto_aprobado.index,
    monto_aprobado.values,
    color=colores[:len(cantidad_por_resultado)]
    )

# Etiquetas con los valores
eje.bar_label(barras, fmt='%.1f M', padding=5)

eje.set_title(f'Monto aprobado por nivel de riesgo — Total: {total_monto_aprobadoMM:,.0f}'.replace(',', '.'))
eje.set_xlabel('Valor aprobado en millones')

plt.tight_layout()
plt.show()

"""### * **Histograma monto de las solicitud**"""

consolidado['cupo_preaprobado_mm'] = consolidado['cupo_preaprobado'] / 1_000_000

consolidado['cupo_preaprobado_mm'].describe()

5000*10000000

figura, eje = plt.subplots(figsize=(8, 4))
eje.hist(consolidado['cupo_preaprobado']/1000000, bins=30, color='#009DAE', edgecolor='white')
eje.set_title('Distribución valor preaprobado Millones')
eje.set_xlabel('valor preaprobado MM')
eje.set_ylabel('Cantidad de solicitudes')
plt.tight_layout()
plt.show()

"""### * **Histograma por edad y cantidad de solicitudes**"""

consolidado['edad'].describe()

figura, eje = plt.subplots(figsize=(8, 4))
eje.hist(consolidado['edad'], bins=30, color='#009DAE', edgecolor='white')
eje.set_title('Distribución de la edad')
eje.set_xlabel('edad')
eje.set_ylabel('Cantidad de solicitudes')
plt.tight_layout()
plt.show()

"""### * Cantidad Solicitudes por fecha y resultado."""

# Pivot_table para graficar cantidad de solicitudes por fecha de solicitud
solicitudes_dia = base_final.pivot_table(index='fecha_solicitud', columns='aprobacion',
                                    values='nombre_cliente', aggfunc='count', fill_value=0)

# Gráfica de solicitudes por fecha de solicitud
figura, eje = plt.subplots(figsize=(10, 4))
eje.plot(solicitudes_dia.index, solicitudes_dia['aprobado a credito'], label='Aprobado Cred')
eje.plot(solicitudes_dia.index, solicitudes_dia['aprobado de contado'], label='Aprobado Cont')
eje.plot(solicitudes_dia.index, solicitudes_dia['no aprobado'], label='No Aprobado')
eje.set_title('Solicitudes diarias')
eje.set_ylabel('Cantidades')
eje.legend()
eje.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""## **13. CONCLUSIONES**



De un total de 5 mil solicitudes que se procesaron con 3045 cédulas únicas se aprobaron con crédito 2278 solicitudes, de contado 17 y no se aprobaron 750 solicitudes. El monto que se aprobó fue de 35.313 millones clasificados en 30711,5 millones en riesgo bajo y 4.601,2 millones en riesgo medio; parariesgo alto no hubo monto aprobado porque estos se aprueba de contado.
En otras palabras, de un monto solicitado de 46.975 millones se aprobó cupo de 35.313 millones.
"""